dataset:
  base_path     : "data/"
  tfrecord_file : "segment-10963653239323173269_1924_000_1944_000_with_camera_labels.tfrecord"
  num_frames    : 200
  start_frame   : 0

object_detection:
  model       : 'darknet'
  result_path : "results/darknet/results_sequence_1_darknet/"

bev_config:
  lim_x       : [0, 50]
  lim_y       : [-25, 25]
  lim_z       : [-1, 3]
  bev_width   : 608
  bev_height  : 608
  conf_thresh : 0.5
  bev_objname : "lidar_bev"